kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zeppelinclaim
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
  selector:
    matchLabels:
      release: stable
