kind: Service
apiVersion: v1
metadata:
  name: zeppelin
  namespace: kube-system
spec:
  ports:
    - port: 8090
      targetPort: 8080
      nodePort: 30080
  selector:
    component: zeppelin
  type: NodePort
