apiVersion: v1
kind: PersistentVolume
metadata:
  name: zeppelin
  namespace: kube-system
  labels:
    release: stable
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /opt
    server: 192.168.140.150
